# Generated by Django 4.0.3 on 2022-07-27 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0004_remove_hat_location_hat_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hat',
            name='location',
        ),
        migrations.AddField(
            model_name='hat',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hats', to='hats_rest.locationvo'),
        ),
    ]
